#!/usr/bin/env bash
# Copies the language-neutral standards from agent-engineering into vendor/ and records the commit.
# Run from anywhere: bash tooling/sync-agent-engineering.sh. Needs git and rsync.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
repo="benpham3206/agent-engineering"
ref="main"
dest="$root/vendor/agent-engineering/standards"
checkout="$(mktemp -d)/agent-engineering"   # the OS clears the temp folder

git -c advice.detachedHead=false clone -q --depth 1 --branch "$ref" "https://github.com/$repo.git" "$checkout"
if [[ ! -d "$checkout/standards" ]]; then
  printf 'sync-agent-engineering: %s has no standards/ at %s\n' "$repo" "$ref" >&2
  exit 1
fi
mkdir -p "$dest"
rsync -a --delete "$checkout/standards/" "$dest/"
{
  printf '# Generated by tooling/sync-agent-engineering.sh. Do not edit by hand.\n'
  printf '# destination upstream ref commit\n'
  printf 'vendor/agent-engineering/standards %s %s %s\n' "$repo" "$ref" "$(git -C "$checkout" rev-parse HEAD)"
} > "$root/vendor/agent-engineering.lock"
cat "$root/vendor/agent-engineering.lock"
