#!/usr/bin/env bash
# Copies agent-engineering's language-neutral layer into this repository and records the commit:
# standards/ into vendor/, and the generic backbone files (role packets, scripts/) to the paths the backbone expects.
# Run from anywhere: bash tooling/sync-agent-engineering.sh. Needs git and rsync. Do not edit the copied files by hand.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
repo="benpham3206/agent-engineering"
ref="main"
checkout="$(mktemp -d)/agent-engineering"   # the OS clears the temp folder
backbone=(
  WORKER_TASK.md ARCHITECT_TASK.md REVIEWER_TASK.md SECURITY_REVIEWER_TASK.md RESEARCH_TASK.md
  scripts/backbone.list scripts/verify-repo.sh scripts/security-check.sh scripts/run-hook.sh
)

git -c advice.detachedHead=false clone -q --depth 1 --branch "$ref" "https://github.com/$repo.git" "$checkout"
for path in standards "${backbone[@]/#/templates/core/}"; do
  if [[ ! -e "$checkout/$path" ]]; then
    printf 'sync-agent-engineering: %s has no %s at %s\n' "$repo" "$path" "$ref" >&2
    exit 1
  fi
done
mkdir -p "$root/vendor/agent-engineering/standards" "$root/scripts"
rsync -a --delete "$checkout/standards/" "$root/vendor/agent-engineering/standards/"
for path in "${backbone[@]}"; do
  cp -p "$checkout/templates/core/$path" "$root/$path"
done
commit="$(git -C "$checkout" rev-parse HEAD)"
{
  printf '# Generated by tooling/sync-agent-engineering.sh. Do not edit by hand.\n'
  printf '# destination upstream ref commit\n'
  printf 'vendor/agent-engineering/standards %s %s %s\n' "$repo" "$ref" "$commit"
  for path in "${backbone[@]}"; do
    printf '%s %s %s %s\n' "$path" "$repo" "$ref" "$commit"
  done
} > "$root/vendor/agent-engineering.lock"
cat "$root/vendor/agent-engineering.lock"
